In [3]:
import numpy as np
A=np.array([[56.0,0,4.4, 68.0],
           [1.2,104.0,52.0,8],
           [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal=A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [6]:
percentage=100*(A/cal.reshape(1,4))
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [8]:
#don't use rank 1 array
b=np.random.rand(5)
print(b)

[0.93992211 0.20941033 0.88830092 0.817018   0.51003012]


In [9]:
print(b.shape)

(5,)


In [11]:
print(b.T)

[0.93992211 0.20941033 0.88830092 0.817018   0.51003012]


In [12]:
print(np.dot(b,b.T))

2.6440339384172864


In [19]:
b=np.random.rand(5,1)
print(b)
assert(b.shape==(5,1))
b=b.reshape(1,5)
print(b)

[[0.40843811]
 [0.50100096]
 [0.62393475]
 [0.72218444]
 [0.95527898]]
[[0.40843811 0.50100096 0.62393475 0.72218444 0.95527898]]


In [15]:
print(b.T)

[[0.16428451 0.55114141 0.77128728 0.26074885 0.74416647]]


In [16]:
print(np.dot(b,b.T))

[[0.0269894  0.090544   0.12671056 0.042837   0.12225503]
 [0.090544   0.30375686 0.42508836 0.14370949 0.41014096]
 [0.12671056 0.42508836 0.59488407 0.20111227 0.57396613]
 [0.042837   0.14370949 0.20111227 0.06798996 0.19404055]
 [0.12225503 0.41014096 0.57396613 0.19404055 0.55378373]]


In [21]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(c)
print(c.shape)

[[-0.41884351  0.79202     2.60095393]
 [ 2.73249787  1.06653987  1.81381422]]
(2, 3)


In [22]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print(c)
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [24]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c)
print(c.shape)

[[ 10.58633726 -14.25055371 -15.91184451 ...  18.01154126  -5.26652619
    8.74409865]
 [ -0.8488912  -10.89640407   5.7090999  ...  28.97528969 -22.59660541
   17.04213963]
 [-18.39191175  -0.56682256   8.912872   ...  14.07111898   8.97529391
    5.34153264]
 ...
 [  7.9140897    8.26277404  -8.40205779 ...  -9.62009287   4.44965674
    0.97641663]
 [  4.01772941 -22.16366306 -17.05298348 ...  -3.59184736   8.08902245
   10.13267953]
 [-22.29364561  -6.81749797 -20.93996681 ...  -5.75896445  -7.59954425
  -22.97871599]]
(12288, 45)


In [26]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)
print(c.shape)

[[-4.87262506e+00  1.44674050e+00  2.39323379e+00]
 [-2.21762109e-02  2.91587362e-02  4.49176131e-02]
 [-2.76066017e-03 -5.11263084e-01  4.97256960e-02]]
(3, 3)


In [28]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])
print(image)
print(image.shape)

[[[0.67826139 0.29380381]
  [0.90714982 0.52835647]
  [0.4215251  0.45017551]]

 [[0.92814219 0.96677647]
  [0.85304703 0.52351845]
  [0.19981397 0.27417313]]

 [[0.60659855 0.00533165]
  [0.10820313 0.49978937]
  [0.34144279 0.94630077]]]
(3, 3, 2)
